# Generated by Django 3.0.6 on 2020-06-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='HardwareUser', ),
    ]
